Cargo.lock
src/config.rs
src/main.rs

after merging the PR from contributor i had to solve some conflicts and some stuff where wrongfully merged.

solving the PR issues as it was done on an old version

---

Cargo.lock
Cargo.toml
soldeer.toml
src/config.rs
src/dependency_downloader.rs
src/janitor.rs
src/main.rs

https://github.com/mario-eth/soldeer/issues/19

implemented clap for a better command line reader

---

Cargo.lock
Cargo.toml
README.md
src/commands.rs
src/config.rs

resolves https://github.com/mario-eth/soldeer/issues/29 and added more info on the helper text

Fixed issue #29 and modified a bit the helper text

---

Cargo.lock
Cargo.toml
src/auth.rs
src/config.rs
src/lib.rs
src/main.rs

Simplified the commands parsing for Foundry integration.

Simplified the commands parsing

---

.gitignore
README.md
src/commands.rs
src/lib.rs
src/versioning.rs

Fixes #70 
Now dry run is available via `soldeer push --dry-run true`

Fixes #70: dry run for push

---

src/dependency_downloader.rs

Download dependencies in parallel

---

src/versioning.rs

Support `.gitignore` alongside `.soldeerignore`

---

Cargo.lock
Cargo.toml
src/lib.rs
src/versioning.rs

Improved the way gitignore and soldeerignore works, now it should be identical with the way git works.
Also solves: https://github.com/mario-eth/soldeer/issues/69

Improved the way gitignore/soldeerignore works

---

Cargo.lock
Cargo.toml
README.md
src/config.rs

Default option when non-config is foundry.toml

---

src/lock.rs

When the lock file does not exist and we don't care, we don't try to create an empty one anymore.
Other minor improvements and naming changes.

perf(lock): better handling of missing lockfile

---

Cargo.lock
Cargo.toml
src/utils.rs

More usage and maintained "officially" by the Cargo team.
Plus some cleanups.

chore(deps): replace simple-home-dir with home

---

Cargo.lock
Cargo.toml
README.md

release 0.3.2

---

Cargo.toml
clippy.toml
crates/commands/tests/tests-install.rs
crates/commands/tests/tests-uninstall.rs
crates/commands/tests/tests-update.rs
crates/core/src/auth.rs
crates/core/src/config.rs
crates/core/src/push.rs

refactor: remove all unwraps

---

.config/nextest.toml

This PR adds a config file for nextest so we automatically retry failing tests and kill stuck tests

ci: add nextest config

---

crates/commands/tests/tests-push.rs

The tests for the `push` command were changing the current directory which lead to race conditions when run with `cargo test`. `cargo-nextest` does not seem to suffer from this.
The fix is to only do this changing of the current dir in one test, and all other tests have a path specified in the cli args.

test(commands): fix tests when run with `cargo test`

---

crates/core/src/config.rs

fix(core): all commands add the `[dependencies]` table in config if missing

---

crates/cli/Cargo.toml
crates/commands/Cargo.toml

adding version to local dependencies so crates will accept the packages

Add core version

---

Cargo.lock
Cargo.toml
crates/commands/Cargo.toml
crates/commands/src/commands/init.rs
crates/commands/src/commands/install.rs
crates/commands/src/commands/login.rs
crates/commands/src/commands/mod.rs
crates/commands/src/commands/push.rs
crates/commands/src/commands/uninstall.rs
crates/commands/src/commands/update.rs
crates/commands/src/lib.rs
crates/commands/tests/tests-init.rs
crates/commands/tests/tests-install.rs
crates/commands/tests/tests-login.rs
crates/commands/tests/tests-push.rs
crates/commands/tests/tests-uninstall.rs
crates/commands/tests/tests-update.rs
crates/core/Cargo.toml
crates/core/src/auth.rs
crates/core/src/config.rs
crates/core/src/errors.rs
crates/core/src/remappings.rs

We had some issues with blocking interactive commands. 
CI wouldn't work with them. I started to solve all the interactive commands by having additional arg that could be passed to skip

185 add cli args to skip interaction for all commands

---

.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/registry_request.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR adds nice issue templates as well as a PR template. Some bad link formatting has been fixed in the contributing guide.

chore: add issue and PR templates

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml

chore(deps): update deps

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/commands/Cargo.toml

prepare for release 0.5.3

---

.github/workflows/release.yml
CHANGELOG.md

This PR changes the release action to use the dedicated github app instead of the default github token. This allows this action to trigger further actions after running, like running tests on PRs opened by the workflow. See [this reference](https://release-plz.dev/docs/github/token#why-you-might-need-further-workflow-runs) for explanations.

ci: use github app token

---

release-plz.toml

chore: update release name template

---

crates/commands/src/commands/push.rs
crates/core/src/utils.rs

fix(commands): canonicalize path in push command

---

Cargo.lock
crates/commands/src/lib.rs
crates/core/Cargo.toml

Closes https://github.com/mario-eth/soldeer/issues/310
Also updates dependencies.

fix(cmd): avoid panicking if logger was already initialized

---

Cargo.toml
crates/cli/src/main.rs
crates/commands/src/commands/init.rs
crates/commands/src/commands/install.rs
crates/commands/src/commands/login.rs
crates/commands/src/commands/push.rs
crates/commands/src/commands/uninstall.rs
crates/commands/src/commands/update.rs
crates/commands/src/lib.rs
crates/commands/src/utils.rs
crates/commands/tests/tests-init.rs
crates/commands/tests/tests-install.rs
crates/commands/tests/tests-login.rs
crates/commands/tests/tests-push.rs
crates/commands/tests/tests-uninstall.rs
crates/commands/tests/tests-update.rs
crates/core/src/auth.rs
crates/core/src/config.rs
crates/core/src/errors.rs
crates/core/src/install.rs
crates/core/src/lock.rs
crates/core/src/push.rs
crates/core/src/registry.rs
crates/core/src/remappings.rs
crates/core/src/update.rs
crates/core/src/utils.rs

This increases the MSRV to 1.88 and edition to 2024.

refactor: rust edition 2024
