mario-eth/soldeer

- src/dependency_downloader.rs
Currently, soldeer would unconditionally create a new folder for each dependency, regardless of whether the installation was successful. If we attempt failed installation repeatedly under different names, it could lead to the accumulation of multiple empty folders within the dependencies directory.
With the PR's changes, a new folder for a dependency will only be created if the installation process completes successfully. This improvement prevents the creation of unnecessary empty folders.
> Improvement: create dependency folders only after successful install

- README.md
- src/commands.rs
- src/config.rs
- src/lib.rs
- src/versioning.rs
- tests/ci/foundry.rs
Fixes the message if one tries to publish a very large package, over 50 MB.
Now you can use `soldeer install` to install the dependencies that are described in the foundry.toml
> Fixes #66 and #50

- src/dependency_downloader.rs
- src/lib.rs
- src/utils.rs
- src/versioning.rs
As discussed in [here](https://github.com/mario-eth/soldeer/issues/67#issuecomment-2192539104) for issue #67, added a user warning when pushing .env or .git/
PS: Missing tests, looking forward to feedback.
> ✨ Added warning when pushing sensitive files

- .gitignore
- Cargo.toml
- src/lib.rs
- src/versioning.rs
When running dry-run the warnings should not appear for .dot files
> Fix some random tests

- src/lib.rs
- src/versioning.rs
Push would cause a Duplicate Filename error as zipping wouldn't be done correctly
> Soldeer push fix

- Cargo.lock
- Cargo.toml
- foundry.toml
- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/janitor.rs
- src/lib.rs
- src/lock.rs
- src/utils.rs
- tests/ci/foundry.rs
Now we can use git to pull dependencies. It supports github and gitlab
Example:
`soldeer install test-project~v1 git@github.com:test/test.git`
`soldeer install test-project~v1 git@gitlab.com:test/test.git`
`soldeer install test-project~v1 https://github.com/test/test.git`
`soldeer install test-project~v1 https://gitlab.com/test/test.git`
Or using custom commit hashes
`soldeer install test-project~v1 git@github.com:test/test.git 345e611cd84bfb4e62c583fa1886c1928bc1a464`
> Adding using git for pulling dependencies

- Cargo.lock
- Cargo.toml
- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/lib.rs
- tests/ci/foundry.rs
I rewrote the git feature to mimic the rust dependency git/rev pattern, also removed the git2 dependency, and just used the CLI.
In the config we will see
```toml
[dependencies]
"dep1" = { version="1", git = "git@github.com/path.git", rev = "23d4edsadsa4s44s4" }
```
while the approach of using the central repository will remain
```toml
[dependencies]
"dep1" = { version="1", url = "https://path" }
```
Now we can use git to pull dependencies. It supports github and gitlab
Example:
```bash
soldeer install test-project~v1 git@github.com:test/test.git
soldeer install test-project~v1 git@gitlab.com:test/test.git
```
```bash
soldeer install test-project~v1 https://github.com/test/test.git
soldeer install test-project~v1 https://gitlab.com/test/test.git
```
Or using custom commit hashes
```bash …
```
> Rewritten git feature

- rustfmt.toml
- src/auth.rs
- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/errors.rs
- src/janitor.rs
- src/lib.rs
- src/lock.rs
- src/remote.rs
- src/utils.rs
- src/versioning.rs
- tests/ci/foundry.rs
The [rustfmt config from foundry](https://github.com/foundry-rs/foundry/blob/master/rustfmt.toml) has been borrowed, and files have been modified to match the styling of foundry in general.
The important points are:
- Imports are always present in a single group (no empty lines) and sorted alphabetically
- Imports from the same crate are joined into a single use statement
- Mod definitions come after the use statements
It's important to note that some of these formatter options are only available on nightly. Hence the command to use is `cargo +nightly fmt` or set the configuration of `rust-analyzer` to have the `rustfmt.extraArgs` option set to `["+nightly"]`.
> style(fmt): update formatter configuration and improve consistency

- src/auth.rs
- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/janitor.rs
- src/lib.rs
- src/lock.rs
- src/utils.rs
- src/versioning.rs
In preparation for improvements on the lockfile and caching topics, I refactored most of the `lock` module and some other things I spotted in various modules.
- More idiomatic Rust syntax
- Better handling of `PathBuf` in various locations
- Lock file is now sorted for minimizing git diffs when updating it
- In case a dependency is added again but was already present in the lock file, the new data will replace the existing data inside the lock file
- Changed the parameters to some functions for clarity
- `janitor::healthcheck_dependency` now takes a reference to `Dependency` instead of name and version
- `janitor::cleanup_dependency` now takes a reference to `Dependency` instead of name and version, and a `CleanupParams` struct as second argument instead of two booleans
- …
> refactor!: cleanup, more idiomatic rust

- .gitignore
- Cargo.lock
- Cargo.toml
- src/auth.rs
- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/errors.rs
- src/janitor.rs
- src/lib.rs
- src/lock.rs
- src/main.rs
- src/remote.rs
- src/utils.rs
- src/versioning.rs
- tests/ci/foundry.rs
Big refactor to adopt idiomatic Rust patterns and improve the existing public API.
The config file (whichever has a `[dependencies]` table between `foundry.toml` and `soldeer.toml`) now has a `[soldeer]` section with the following format and defaults:
```toml
[soldeer]
remappings_generated = true
remappings_regenerate = false
remappings_version = true
remappings_prefix = ""
remappings_location = "txt"
```
Remappings are now properly managed by Soldeer if desired. They can be updated inside the `foundry.toml` file if that file is also used for `[dependencies]`.
Remappings in the `[profile.default]` are always managed if `remappings_generated = true`. Other profiles only get managed if they already contain a `remappings` array.
If `remappings_regenerate = false`, then existing remappings …
> refactor!: big rewrite

- src/config.rs
- src/lib.rs
During the `update` command, the remappings were not correctly generated if no remappings already existed (such as when the user manually deletes the remappings.txt file)
To improve performance and aid in testing, the following changes were made:
- `remappings_txt` takes an additionnal parameter for the config file path
- `remappings_foundry`  takes an additionnal parameter for the config file path
> fix(config)!: fix remappings logic and logging

- Cargo.lock
- Cargo.toml
- src/auth.rs
- src/config.rs
- src/lock.rs
- src/remote.rs
No need for `serde_derive` since we can just enable the `derive` feature on `serde`. Updated the cargo lockfile.
> chore: update deps and remove serde_derive

- src/config.rs
- src/dependency_downloader.rs
- src/lib.rs
Now that downloads happen in parallel, we must be sure to order the download results (zip url and hash) in a consistent order since we iterate together with the the original list in `lib.rs` (via `zip()`)
> fix: parallel downloads order

- src/commands.rs
- src/config.rs
- src/dependency_downloader.rs
- src/errors.rs
- src/janitor.rs
- src/lib.rs
- tests/ci/foundry.rs
Solves the recursive dependencies.
if you set --recursive-deps when you run install or update  or you set the config
[soldeer]
recursive-deps = true
Soldeer will install automatically the submodule dependencies and soldeer dependencies of the dependency you want to install. 
Closes https://github.com/mario-eth/soldeer/issues/115
> Recursive Dependencies

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/dependency_downloader.rs
- src/janitor.rs
- src/lib.rs
- src/remote.rs
Solved some hot fixes regarding the way the dependencies where handled if only the version was specified in the config. Resolved the fact that git revision was not always saved in the config, extra remappings tests
> Hotfixes and extra tests before 0.3.0

- Cargo.lock
- Cargo.toml
- src/dependency_downloader.rs
- src/lib.rs
- src/lock.rs
- src/utils.rs
- src/versioning.rs
This is the first step towards having a way to skip install of already installed dependencies. The next step will involve a refactor for the download/extract pipeline and is out of the scope of this PR.
This checksum would only be used for zip dependencies. Deps cloned with git could be checked for integrity with `git diff` for example, and a full re-download/clone is probably not necessary in case of failed integrity check. A simple forced checkout should suffice.
Took the chance to refactor the dir-walking for the `push` command.
- `unzip_dependencies` returns a `Result<Vec<Option<IntegrityChecksum>>>`
- `unzip_dependency` returns a `Result<IntegrityChecksum>`
- `write_lock` takes in an additional parameter `integrity_checksums: &[Option<IntegrityChecksum>]`
- `sha256_digest` was …
> feat: add integrity checksum to lockfile

- Cargo.toml
- src/config.rs
- src/lib.rs
- src/lock.rs
- tests/ci/foundry.rs
These are copied from Foundry. I've not enabled them all, even if mostly auto-fixable, to not be too invasive because as I understand you're working on a big refactor for 0.4.0.
> chore: enable some more lints

- Cargo.lock
- Cargo.toml
Also removing
```
[profile.test]
opt-level = 2
```
as it does not speed up tests meaningfully and causes a recompilation between `cargo build` and `cargo test`.
> chore: remove unused dev dep env_logger

- src/utils.rs
Previously, the `hash_folder` function was not properly normalizing paths to be relative to the root of the considered directory. This lead to hash inconsistencies between environments. It didn't show up in unit tests because the input path was itself relative. A new test has been added that shows the now correct behavior.
> fix(utils): always consider relative path in hashing

- crates/commands/src/commands/mod.rs
- crates/commands/src/lib.rs
- crates/commands/tests/tests-init.rs
- crates/commands/tests/tests-install.rs
- crates/core/src/download.rs
- crates/core/src/install.rs
Took the chance to refactor the `download_file` function and its usage, because it was not exactly behaving as described in the docs. Now the zip files are downloaded in the `dependencies` folder with the name of the dependency and the zip extension.
Also renammed the `Subcommands` enum to `Command` (because enum should be singular and it's shorter).
> refactor!: minor refactor and integration tests

- crates/core/src/download.rs
- crates/core/src/remappings.rs
- crates/core/src/utils.rs
Existing remappings can now be kept even during an update which changes the version string of the dependency folder.
The old path is replaced with the new path, keeping any path customization intact.
Example:
```toml
[dependencies]
my-lib = "1"
```
```
my-lib-foobar/=dependencies/my-lib-1.1.0/src/
```
```
my-lib-foobar/=dependencies/my-lib-1.2.0/src/
```
> feat(core): improve remappings matching

- crates/commands/src/commands/init.rs
- crates/commands/tests/tests-init.rs
- crates/core/src/config.rs
The `init` command now adds the "dependencies" folder to the `profile.default.libs` foundry config item if the foundry.toml file exists.
> feat(commands): update libs in foundry config during init

- .github/workflows/rust.yml
Slightly faster tests in CI (at least on macOS and Linux). I expect the more tests we have, the more benefit we will have from nextest.
> ci: speed up test by using cargo-nextest

- crates/cli/src/main.rs
1. Addition of a banner displayed with useful information 
- There was an earlier PR on the `main` branch, but as advised to put it in `release/v0.4.0`
> feat(cli): add banner

- Cargo.lock
- crates/core/src/config.rs
- crates/core/src/install.rs
- crates/core/src/lock.rs
The newest version of `bon` changed the derive syntax. While the current code is still compatible with this newer version, the syntax has been deprecated and it's a good idea to update to the new syntax (also to make CI happy)
> refactor: use new syntax for bon builders

- README.md
Due to how cargo packages crates from a workspace, the relative paths used in the readme do not work when visiting [crates.io](https://crates.io/crates/soldeer) (see https://github.com/rust-lang/crates.io/issues/9927).
This is easily fixed by using absolute URLs into the link.
> docs: fix links in README for crates.io

- crates/commands/tests/tests-install.rs
- crates/core/src/registry.rs
Previously, the `parse_version_req` function didn't accept `*` as a valid version requirement string. This has now changed and it is accepted, meaning `>=0.0.0`.
Note: this wildcard version requirement does not match pre-release versions.
Closes #223
> fix(core): accept wildcard (star) version

- Cargo.lock
- crates/core/src/utils.rs
In the `hash_folder` function, the `ignore::walk::WalkParallel` used to walk the directory to hash was configured [by default](https://docs.rs/ignore/0.4.23/ignore/struct.WalkBuilder.html#method.standard_filters) to honor parent `.gitignore` files, global `.gitignore` files and to require that the folder be inside of a git repository to honor `.gitignore` files. This lead to unreproducible integrity checksums being computed.
Now, parent and global files are ignored, and `.gitignore` files are honored even if the dependency is installed outside of a git repo.
Closes #232
> fix(core): gitignore config for integrity checksum

- Cargo.lock
- USAGE.md
- crates/commands/src/commands/install.rs
- crates/commands/tests/tests-init.rs
- crates/commands/tests/tests-install.rs
- crates/core/src/config.rs
- crates/core/src/lock.rs
- crates/core/src/utils.rs
> fix(core): remove hardcoded git domains

- crates/commands/src/commands/push.rs
- crates/core/src/errors.rs
- crates/core/src/push.rs
Fixes #246 
I have decided to introduce a wrapper around validating version of the package for the push command rather than inlining it with the intent that perhaps in the future semver could be enforced, or other validation performed.
> fix(push): ensure version is non-empty when pushing to registry

- crates/core/src/registry.rs
Previously, if some versions in the API response could not be parsed as SemVer, the resolution would default to using the latest version. Now, this creates and error unless we can find an exact match for the version specifier of the dependency.
> fix(registry): version resolution when no SemVer

- release-plz.toml
Release-plz uses by a default a tag which is prefixed with the crate name, but we don't need this as all crates have the same version number in sync.
https://release-plz.dev/docs/extra/single-tag
> chore: make release-plz use a single tag

- crates/commands/tests/tests-install.rs
- crates/core/src/download.rs
- crates/core/src/errors.rs
- crates/core/src/install.rs
- crates/core/src/utils.rs
When dependencies are installed from the registry or any zip URL, they often do not constitute a valid git repository (missing `.git` folder) which means that installing git submodules inside those requires special care.
The repositories need to be repaired, that is:
- `git init`
- `git submodule add` for each submodule in the `.gitmodules` file
This PR adds this logic and also makes sure that potential soldeer dependencies of subdependencies are installed recursively.
An unfortunate consequence of the missing metadata is that re-adding the submodules will clone them with the latest commit on the specified branch. So if a dependency was referencing an old commit when the zip was created, and we install it later, we might install a different version of the sub-dependency. Users who wish to …
> fix(core): recursive subdependencies install

- Cargo.toml
- clippy.toml
- crates/core/src/download.rs
- flake.lock
- flake.nix
Added a flake for development since I'm always struggling with missing openSSL on nixOS. Also silenced a deprecation warning.
> chore: add nix flake and fix clippy
